---
http_interactions:
- request:
    method: get
    uri: http://localhost:3000/api/v1/chat_service?task=water%20plants
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v2.7.11
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 500
      message: Internal Server Error
    headers:
      Content-Type:
      - application/json; charset=UTF-8
      X-Request-Id:
      - 31470b97-f08b-411b-970c-3ecc01cb17c2
      X-Runtime:
      - '0.012800'
      Server-Timing:
      - sql.active_record;dur=2.81
      Content-Length:
      - '9312'
    body:
      encoding: UTF-8
      string: '{"status":500,"error":"Internal Server Error","exception":"#\u003cActiveRecord::PendingMigrationError:\"\\n\\nMigrations
        are pending. To resolve this issue, run:\\n\\n        bin/rails db:migrate
        RAILS_ENV=development\\n\\nYou have 2 pending migrations:\\n\\n20230913161805_create_tasks.rb\\n20230915023139_edit_event_date_column.rb\\n\\n\\n\"\u003e","traces":{"Application
        Trace":[],"Framework Trace":[{"exception_object_id":11240,"id":0,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:662:in `check_pending!''"},{"exception_object_id":11240,"id":1,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:627:in `block (2 levels) in call''"},{"exception_object_id":11240,"id":2,"trace":"activesupport
        (7.0.8) lib/active_support/file_update_checker.rb:83:in `execute''"},{"exception_object_id":11240,"id":3,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:632:in `block in call''"},{"exception_object_id":11240,"id":4,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:624:in `synchronize''"},{"exception_object_id":11240,"id":5,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:624:in `call''"},{"exception_object_id":11240,"id":6,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call''"},{"exception_object_id":11240,"id":7,"trace":"activesupport
        (7.0.8) lib/active_support/callbacks.rb:99:in `run_callbacks''"},{"exception_object_id":11240,"id":8,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/callbacks.rb:26:in `call''"},{"exception_object_id":11240,"id":9,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/executor.rb:14:in `call''"},{"exception_object_id":11240,"id":10,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call''"},{"exception_object_id":11240,"id":11,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call''"},{"exception_object_id":11240,"id":12,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call''"},{"exception_object_id":11240,"id":13,"trace":"railties
        (7.0.8) lib/rails/rack/logger.rb:40:in `call_app''"},{"exception_object_id":11240,"id":14,"trace":"railties
        (7.0.8) lib/rails/rack/logger.rb:25:in `block in call''"},{"exception_object_id":11240,"id":15,"trace":"activesupport
        (7.0.8) lib/active_support/tagged_logging.rb:99:in `block in tagged''"},{"exception_object_id":11240,"id":16,"trace":"activesupport
        (7.0.8) lib/active_support/tagged_logging.rb:37:in `tagged''"},{"exception_object_id":11240,"id":17,"trace":"activesupport
        (7.0.8) lib/active_support/tagged_logging.rb:99:in `tagged''"},{"exception_object_id":11240,"id":18,"trace":"railties
        (7.0.8) lib/rails/rack/logger.rb:25:in `call''"},{"exception_object_id":11240,"id":19,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/remote_ip.rb:93:in `call''"},{"exception_object_id":11240,"id":20,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/request_id.rb:26:in `call''"},{"exception_object_id":11240,"id":21,"trace":"rack
        (2.2.8) lib/rack/runtime.rb:22:in `call''"},{"exception_object_id":11240,"id":22,"trace":"activesupport
        (7.0.8) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in
        `call''"},{"exception_object_id":11240,"id":23,"trace":"actionpack (7.0.8)
        lib/action_dispatch/middleware/server_timing.rb:61:in `block in call''"},{"exception_object_id":11240,"id":24,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events''"},{"exception_object_id":11240,"id":25,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/server_timing.rb:60:in `call''"},{"exception_object_id":11240,"id":26,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/executor.rb:14:in `call''"},{"exception_object_id":11240,"id":27,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/static.rb:23:in `call''"},{"exception_object_id":11240,"id":28,"trace":"rack
        (2.2.8) lib/rack/sendfile.rb:110:in `call''"},{"exception_object_id":11240,"id":29,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/host_authorization.rb:138:in `call''"},{"exception_object_id":11240,"id":30,"trace":"railties
        (7.0.8) lib/rails/engine.rb:530:in `call''"},{"exception_object_id":11240,"id":31,"trace":"puma
        (5.6.7) lib/puma/configuration.rb:252:in `call''"},{"exception_object_id":11240,"id":32,"trace":"puma
        (5.6.7) lib/puma/request.rb:77:in `block in handle_request''"},{"exception_object_id":11240,"id":33,"trace":"puma
        (5.6.7) lib/puma/thread_pool.rb:340:in `with_force_shutdown''"},{"exception_object_id":11240,"id":34,"trace":"puma
        (5.6.7) lib/puma/request.rb:76:in `handle_request''"},{"exception_object_id":11240,"id":35,"trace":"puma
        (5.6.7) lib/puma/server.rb:443:in `process_client''"},{"exception_object_id":11240,"id":36,"trace":"puma
        (5.6.7) lib/puma/thread_pool.rb:147:in `block in spawn_thread''"}],"Full Trace":[{"exception_object_id":11240,"id":0,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:662:in `check_pending!''"},{"exception_object_id":11240,"id":1,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:627:in `block (2 levels) in call''"},{"exception_object_id":11240,"id":2,"trace":"activesupport
        (7.0.8) lib/active_support/file_update_checker.rb:83:in `execute''"},{"exception_object_id":11240,"id":3,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:632:in `block in call''"},{"exception_object_id":11240,"id":4,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:624:in `synchronize''"},{"exception_object_id":11240,"id":5,"trace":"activerecord
        (7.0.8) lib/active_record/migration.rb:624:in `call''"},{"exception_object_id":11240,"id":6,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call''"},{"exception_object_id":11240,"id":7,"trace":"activesupport
        (7.0.8) lib/active_support/callbacks.rb:99:in `run_callbacks''"},{"exception_object_id":11240,"id":8,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/callbacks.rb:26:in `call''"},{"exception_object_id":11240,"id":9,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/executor.rb:14:in `call''"},{"exception_object_id":11240,"id":10,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call''"},{"exception_object_id":11240,"id":11,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call''"},{"exception_object_id":11240,"id":12,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call''"},{"exception_object_id":11240,"id":13,"trace":"railties
        (7.0.8) lib/rails/rack/logger.rb:40:in `call_app''"},{"exception_object_id":11240,"id":14,"trace":"railties
        (7.0.8) lib/rails/rack/logger.rb:25:in `block in call''"},{"exception_object_id":11240,"id":15,"trace":"activesupport
        (7.0.8) lib/active_support/tagged_logging.rb:99:in `block in tagged''"},{"exception_object_id":11240,"id":16,"trace":"activesupport
        (7.0.8) lib/active_support/tagged_logging.rb:37:in `tagged''"},{"exception_object_id":11240,"id":17,"trace":"activesupport
        (7.0.8) lib/active_support/tagged_logging.rb:99:in `tagged''"},{"exception_object_id":11240,"id":18,"trace":"railties
        (7.0.8) lib/rails/rack/logger.rb:25:in `call''"},{"exception_object_id":11240,"id":19,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/remote_ip.rb:93:in `call''"},{"exception_object_id":11240,"id":20,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/request_id.rb:26:in `call''"},{"exception_object_id":11240,"id":21,"trace":"rack
        (2.2.8) lib/rack/runtime.rb:22:in `call''"},{"exception_object_id":11240,"id":22,"trace":"activesupport
        (7.0.8) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in
        `call''"},{"exception_object_id":11240,"id":23,"trace":"actionpack (7.0.8)
        lib/action_dispatch/middleware/server_timing.rb:61:in `block in call''"},{"exception_object_id":11240,"id":24,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events''"},{"exception_object_id":11240,"id":25,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/server_timing.rb:60:in `call''"},{"exception_object_id":11240,"id":26,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/executor.rb:14:in `call''"},{"exception_object_id":11240,"id":27,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/static.rb:23:in `call''"},{"exception_object_id":11240,"id":28,"trace":"rack
        (2.2.8) lib/rack/sendfile.rb:110:in `call''"},{"exception_object_id":11240,"id":29,"trace":"actionpack
        (7.0.8) lib/action_dispatch/middleware/host_authorization.rb:138:in `call''"},{"exception_object_id":11240,"id":30,"trace":"railties
        (7.0.8) lib/rails/engine.rb:530:in `call''"},{"exception_object_id":11240,"id":31,"trace":"puma
        (5.6.7) lib/puma/configuration.rb:252:in `call''"},{"exception_object_id":11240,"id":32,"trace":"puma
        (5.6.7) lib/puma/request.rb:77:in `block in handle_request''"},{"exception_object_id":11240,"id":33,"trace":"puma
        (5.6.7) lib/puma/thread_pool.rb:340:in `with_force_shutdown''"},{"exception_object_id":11240,"id":34,"trace":"puma
        (5.6.7) lib/puma/request.rb:76:in `handle_request''"},{"exception_object_id":11240,"id":35,"trace":"puma
        (5.6.7) lib/puma/server.rb:443:in `process_client''"},{"exception_object_id":11240,"id":36,"trace":"puma
        (5.6.7) lib/puma/thread_pool.rb:147:in `block in spawn_thread''"}]}}'
  recorded_at: Sat, 16 Sep 2023 22:52:05 GMT
recorded_with: VCR 6.2.0
